# yaml-language-server: $schema=https://raw.githubusercontent.com/gitpod-io/gitpod/main/components/gitpod-protocol/data/gitpod-schema.json
image: quay.io/gitpodified-workspace-images/full:commit-4830bab
checkoutLocation: csb-dev/base-images
workspaceLocation: csb-dev/base-images
tasks:
  - name: Setup
    before: |
      .gitpod/scripts/docker-cli-login
      direnv allow
    init:
      docker pull buildpack-deps:bullseye