# yaml-language-server: $schema=https://raw.githubusercontent.com/gitpod-io/gitpod/main/components/gitpod-protocol/data/gitpod-schema.json
image: quay.io/gitpodified-workspace-images/full:commit-4830bab